version: '3.9'
networks:
  ottct-main-network:
    driver: bridge
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    hostname: localstack
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal sqs list-queues
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - 4566:4566
    environment:
      SERVICES: "sqs,ses"
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      AWS_REGION: 'us-east-1'
      HOSTNAME_EXTERNAL: 'localstack'
    volumes:
      - "./init-scripts://etc/localstack/init/ready.d/"
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ottct-main-network
  app:
    build: .
    container_name: app
    image: ottct-main-service:latest
    environment:
      DB_URL: 'postgres://postgres:tests@db:5432/ottct_main_service'
      SECRET_KEY: 's+76qrrI53tqP666lQla3t+pitXrAsYQQbEn/55JQKA='
      TWITTER_BEARER_KEY: 'AAAAAAAAAAAAAAAAAAAAACXAcgEAAAAAMFkd4RQMKRSjvXUQGIrdZAHNJjg%3DLYqfisQPqvbuXeo0FjwYhrGqJ0eU6MVdHsLIqdvJ368MfZAq9o'
      PREDICTOR_URL: 'http://ml-main:8080/predict'
      SENDER: 'admin@admin.com'
      AWS_ENDPOINT_URL: 'http://localstack:4566'
      FAKE_NEWS_QUEUE_URL: 'http://localstack:4566/000000000000/default-fake-news'
      AWS_REGION: 'us-east-1'
    ports:
      - 8080:8080
    networks:
      - ottct-main-network
    depends_on:
      db:
        condition: service_healthy
  ml:
    container_name: ml-main
    image: ml
    ports:
      - 8081:8080
    networks:
      - ottct-main-network
  db:
    image: postgres:13.3-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tests
    restart: on-failure
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    command:
      - /bin/sh
      - -c
      - |
        echo 'psql -v ON_ERROR_STOP=1 --username "$$POSTGRES_USER" -c "CREATE DATABASE ottct_main_service";' >> /docker-entrypoint-initdb.d/init.sh;
        docker-entrypoint.sh postgres
    networks:
      - ottct-main-network
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "8082:8080"
   volumes:
      - "./docs/api.yaml:/api.yaml"
   environment:
      SWAGGER_JSON: '/api.yaml'
