openapi: 3.0.3
info:
  title: OTTCT API
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /v0/entities:
    get:
      summary: Get Entities
      tags:
        - v0
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    twitterId:
                      type: string
                    displayName:
                      type: string
                    twitterHandle:
                      type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v0/subscribe:
    post:
      summary: Subscribe to alerts
      tags:
        - v0
      requestBody:
        description: Subscribe request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                entityId:
                  type: string
              required:
                - email
                - entityId
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v0/analytics:
    get:
      summary: Get Tweets Analytics
      tags:
        - v0
      parameters:
        - name: entityId
          in: query
          description: The ID of the entity to get tweets for
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: The starting date-time for the tweet search
          required: false
          schema:
            type: string
            format: date-time
            default: now-1hr
        - name: to
          in: query
          description: The ending date-time for the tweet search
          required: false
          schema:
            type: string
            format: date-time
            default: now
        - name: maxResults
          in: query
          description: The maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 5
            maximum: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total number of results.
                        example: 100
                      authentic:
                        type: number
                        format: float
                        description: The percentage of authentic results.
                        example: 92.2
                      unauthentic:
                        type: number
                        format: float
                        description: The percentage of unauthentic results.
                        example: 0.8
                    required:
                      - total
                      - authentic
                      - unauthentic
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/signup:
    post:
      summary: Signup
      tags:
        - v1
      requestBody:
        description: Signup request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/auth:
    post:
      summary: Authenticate
      tags:
        - v1
      requestBody:
        description: Authenticate request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/entities:
    get:
      summary: Get Entities
      tags:
        - v1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    twitterId:
                      type: string
                    displayName:
                      type: string
                    twitterHandle:
                      type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/subscribe:
    get:
      summary: Get Subscriptions
      tags:
        - v1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    twitterId:
                      type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
  /v1/subscribe/{entityId}:
    post:
      summary: Update Subscription
      tags:
        - v1
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: entityId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subscribe:
                  type: boolean
              required:
                - subscribe
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/analytics:
    get:
      summary: Get Tweets
      tags:
        - v1
      security:
        - bearerAuth: []
      parameters:
        - name: entityId
          in: query
          description: The ID of the entity to get tweets for
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: The starting date-time for the tweet search
          required: false
          schema:
            type: string
            format: date-time
            default: now-1hr
        - name: to
          in: query
          description: The ending date-time for the tweet search
          required: false
          schema:
            type: string
            format: date-time
            default: now
        - name: maxResults
          in: query
          description: The maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 5
            maximum: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: The total number of results.
                        example: 100
                      authentic:
                        type: number
                        format: float
                        description: The percentage of authentic results.
                        example: 92.2
                      unauthentic:
                        type: number
                        format: float
                        description: The percentage of unauthentic results.
                        example: 0.8
                    required:
                      - total
                      - authentic
                      - unauthentic
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'