openapi: 3.0.3
info:
  title: OTTCT API
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /v1/signup:
    post:
      summary: Signup
      requestBody:
        description: Signup request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/auth:
    post:
      summary: Authenticate
      requestBody:
        description: Authenticate request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/entities:
    get:
      summary: Get Entities
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    twitterId:
                      type: string
                    displayName:
                      type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/subscribe:
    get:
      summary: Get Subscriptions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    twitterId:
                      type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
  /v1/subscribe/{entityId}:
    post:
      summary: Update Subscription
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: entityId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subscribe:
                  type: boolean
              required:
                - subscribe
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/tweets:
    get:
      summary: Get Tweets
      security:
        - bearerAuth: []
      parameters:
        - name: entityId
          in: query
          description: The ID of the entity to get tweets for
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: The starting date-time for the tweet search
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: The ending date-time for the tweet search
          required: true
          schema:
            type: string
            format: date-time
        - name: maxResults
          in: query
          description: The maximum number of results to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tweets:
                    type: array
                    items:
                        type: object
                        properties:
                          id:
                            type: string
                          content:
                            type: string
                          createdAt:
                            type: string
                            format: date-time
                          realnessScore:
                            type: integer
                            format: int32
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'